[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
PYTHON_VERSION = "3.11"

# Database Configuration
DATABASE_URL = "${{secrets.DATABASE_URL}}"
SUPABASE_URL = "${{secrets.SUPABASE_URL}}"
SUPABASE_KEY = "${{secrets.SUPABASE_KEY}}"

# Model Configuration
MODEL_VERSION = "v1.0"
TRAINING_SCHEDULE = "0 2 * * 0"  # Ogni domenica alle 02:00 UTC
DEBUG = "false"

# Performance
WORKERS = "1"
TIMEOUT = "120"
MAX_REQUESTS = "1000"
MAX_REQUESTS_JITTER = "100"