[providers]
python = "3.10"

[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install -r api/requirements.txt"]

[start]
cmd = "cd api && python -m uvicorn ml_prediction_service:app --host 0.0.0.0 --port $PORT"
