-- Aggiungi pesi default per tutte le coppie forex Major e Minor
-- Esegui questo nel Supabase SQL Editor

INSERT INTO ml_weight_optimization (symbol, session, regime) VALUES
  -- EURUSD (già presente ma aggiungiamo i missing)
  ('EURUSD', 'ASIAN', 'TREND_BEARISH'),
  ('EURUSD', 'LONDON', 'RANGE'),
  ('EURUSD', 'LONDON', 'TREND_BEARISH'),
  ('EURUSD', 'NY', 'RANGE'),
  ('EURUSD', 'NY', 'TREND_BEARISH'),
  ('EURUSD', 'OVERLAP', 'RANGE'),
  ('EURUSD', 'OVERLAP', 'TREND_BULLISH'),
  ('EURUSD', 'OVERLAP', 'TREND_BEARISH'),

  -- GBPUSD
  ('GBPUSD', 'ASIAN', 'RANGE'),
  ('GBPUSD', 'ASIAN', 'TREND_BULLISH'),
  ('GBPUSD', 'ASIAN', 'TREND_BEARISH'),
  ('GBPUSD', 'LONDON', 'RANGE'),
  ('GBPUSD', 'LONDON', 'TREND_BULLISH'),
  ('GBPUSD', 'LONDON', 'TREND_BEARISH'),
  ('GBPUSD', 'NY', 'RANGE'),
  ('GBPUSD', 'NY', 'TREND_BULLISH'),
  ('GBPUSD', 'NY', 'TREND_BEARISH'),
  ('GBPUSD', 'OVERLAP', 'RANGE'),
  ('GBPUSD', 'OVERLAP', 'TREND_BULLISH'),
  ('GBPUSD', 'OVERLAP', 'TREND_BEARISH'),

  -- USDJPY
  ('USDJPY', 'ASIAN', 'RANGE'),
  ('USDJPY', 'ASIAN', 'TREND_BULLISH'),
  ('USDJPY', 'ASIAN', 'TREND_BEARISH'),
  ('USDJPY', 'LONDON', 'RANGE'),
  ('USDJPY', 'LONDON', 'TREND_BULLISH'),
  ('USDJPY', 'LONDON', 'TREND_BEARISH'),
  ('USDJPY', 'NY', 'RANGE'),
  ('USDJPY', 'NY', 'TREND_BULLISH'),
  ('USDJPY', 'NY', 'TREND_BEARISH'),
  ('USDJPY', 'OVERLAP', 'RANGE'),
  ('USDJPY', 'OVERLAP', 'TREND_BULLISH'),
  ('USDJPY', 'OVERLAP', 'TREND_BEARISH'),

  -- USDCHF
  ('USDCHF', 'ASIAN', 'RANGE'),
  ('USDCHF', 'ASIAN', 'TREND_BULLISH'),
  ('USDCHF', 'ASIAN', 'TREND_BEARISH'),
  ('USDCHF', 'LONDON', 'RANGE'),
  ('USDCHF', 'LONDON', 'TREND_BULLISH'),
  ('USDCHF', 'LONDON', 'TREND_BEARISH'),
  ('USDCHF', 'NY', 'RANGE'),
  ('USDCHF', 'NY', 'TREND_BULLISH'),
  ('USDCHF', 'NY', 'TREND_BEARISH'),
  ('USDCHF', 'OVERLAP', 'RANGE'),
  ('USDCHF', 'OVERLAP', 'TREND_BULLISH'),
  ('USDCHF', 'OVERLAP', 'TREND_BEARISH'),

  -- AUDUSD
  ('AUDUSD', 'ASIAN', 'RANGE'),
  ('AUDUSD', 'ASIAN', 'TREND_BULLISH'),
  ('AUDUSD', 'ASIAN', 'TREND_BEARISH'),
  ('AUDUSD', 'LONDON', 'RANGE'),
  ('AUDUSD', 'LONDON', 'TREND_BULLISH'),
  ('AUDUSD', 'LONDON', 'TREND_BEARISH'),
  ('AUDUSD', 'NY', 'RANGE'),
  ('AUDUSD', 'NY', 'TREND_BULLISH'),
  ('AUDUSD', 'NY', 'TREND_BEARISH'),
  ('AUDUSD', 'OVERLAP', 'RANGE'),
  ('AUDUSD', 'OVERLAP', 'TREND_BULLISH'),
  ('AUDUSD', 'OVERLAP', 'TREND_BEARISH'),

  -- NZDUSD
  ('NZDUSD', 'ASIAN', 'RANGE'),
  ('NZDUSD', 'ASIAN', 'TREND_BULLISH'),
  ('NZDUSD', 'ASIAN', 'TREND_BEARISH'),
  ('NZDUSD', 'LONDON', 'RANGE'),
  ('NZDUSD', 'LONDON', 'TREND_BULLISH'),
  ('NZDUSD', 'LONDON', 'TREND_BEARISH'),
  ('NZDUSD', 'NY', 'RANGE'),
  ('NZDUSD', 'NY', 'TREND_BULLISH'),
  ('NZDUSD', 'NY', 'TREND_BEARISH'),
  ('NZDUSD', 'OVERLAP', 'RANGE'),
  ('NZDUSD', 'OVERLAP', 'TREND_BULLISH'),
  ('NZDUSD', 'OVERLAP', 'TREND_BEARISH'),

  -- EURGBP
  ('EURGBP', 'ASIAN', 'RANGE'),
  ('EURGBP', 'ASIAN', 'TREND_BULLISH'),
  ('EURGBP', 'ASIAN', 'TREND_BEARISH'),
  ('EURGBP', 'LONDON', 'RANGE'),
  ('EURGBP', 'LONDON', 'TREND_BULLISH'),
  ('EURGBP', 'LONDON', 'TREND_BEARISH'),
  ('EURGBP', 'NY', 'RANGE'),
  ('EURGBP', 'NY', 'TREND_BULLISH'),
  ('EURGBP', 'NY', 'TREND_BEARISH'),
  ('EURGBP', 'OVERLAP', 'RANGE'),
  ('EURGBP', 'OVERLAP', 'TREND_BULLISH'),
  ('EURGBP', 'OVERLAP', 'TREND_BEARISH'),

  -- EURJPY
  ('EURJPY', 'ASIAN', 'RANGE'),
  ('EURJPY', 'ASIAN', 'TREND_BULLISH'),
  ('EURJPY', 'ASIAN', 'TREND_BEARISH'),
  ('EURJPY', 'LONDON', 'RANGE'),
  ('EURJPY', 'LONDON', 'TREND_BULLISH'),
  ('EURJPY', 'LONDON', 'TREND_BEARISH'),
  ('EURJPY', 'NY', 'RANGE'),
  ('EURJPY', 'NY', 'TREND_BULLISH'),
  ('EURJPY', 'NY', 'TREND_BEARISH'),
  ('EURJPY', 'OVERLAP', 'RANGE'),
  ('EURJPY', 'OVERLAP', 'TREND_BULLISH'),
  ('EURJPY', 'OVERLAP', 'TREND_BEARISH')

ON CONFLICT (symbol, session, regime) DO NOTHING;

-- Verifica quante righe sono state inserite
SELECT COUNT(*) as total_weight_configs FROM ml_weight_optimization;

-- Verifica per simbolo
SELECT symbol, COUNT(*) as configs
FROM ml_weight_optimization
GROUP BY symbol
ORDER BY symbol;
