project_id = "rvopmdflnecyrwrzhyfy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://cash-revolution.com"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://localhost:3000/reset-password",
  "https://781f6820-a889-430b-9c1a-dd28bdb32c37.lovableproject.com",
  "https://781f6820-a889-430b-9c1a-dd28bdb32c37.lovableproject.com/reset-password",
  "https://cash-revolution.com/login",
  "https://cash-revolution.com/reset-password"
]
jwt_expiry = 3600
enable_anonymous_sign_ins = false
enable_signup = true

[functions.generate-ai-signals]
verify_jwt = false  # Allow internal calls from auto-oanda-trader

[functions.mt5-trade-signals]
verify_jwt = false

[functions.ml-trading-optimizer]
verify_jwt = false

[functions.ml-performance-tracker]
verify_jwt = false

[functions.ml-historical-training]
verify_jwt = false

[functions.oanda-market-data]
verify_jwt = false

[functions.fetch-financial-news]
verify_jwt = false

[functions.fetch-economic-calendar]
verify_jwt = false

[functions.update-economic-calendar]
verify_jwt = false

[functions.mt5-trade-update]
verify_jwt = false

[functions.reset-mt5-signals]  
verify_jwt = false

[functions.welcome-email]
verify_jwt = false

[functions.password-reset-email]
verify_jwt = false

[functions.auth-email-handler]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.crypto-price-feed]
verify_jwt = false

[functions.create-stripe-setup]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.verify-crypto-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-payment-qr]
verify_jwt = false

[functions.crypto-renewal-reminder]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.realtime-trade-webhook]
verify_jwt = false

[functions.llm-sentiment]
verify_jwt = false

[functions.auto-oanda-trader]
verify_jwt = false

[functions.expire-trials]
verify_jwt = false

[functions.notify-signal]
verify_jwt = false

[functions.heartbeat]
verify_jwt = false
